#!/bin/bash
tmp=$IFS
IFS='
'
for var in $(ps -u $(basename $HOME) | grep server)
do 
    pid=$(echo $var | awk '{print $1}')
    pname=$(echo $var | awk '{print $4}')

    if kill -9 $pid
    then 
        echo "$pname stopped"
    else
        echo "$pname can't be stopped"
    fi
done

cond=$(ps -u $(basename $HOME) | grep server | wc -l)
while [ $cond -gt 0 ]
do
    sleep 1
    cond=$(ps -u $(basename $HOME) | grep server | wc -l)
    echo "server num:$cond"
done
